export const SET_STARSHIPS = 'SET_STARSHIPS'
export const SET_FILTERED_STARSHIPS = 'SET_FILTERED_STARSHIPS'
export const SET_FILTERS = 'SET_FILTERS'
export const SET_LOADING = 'SET_LOADING'

export const SET_PRODUCTS = 'SET_PRODUCTS'
